# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20161018_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.Project'),
        ),
    ]
