# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20161019_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='metric',
            field=models.ManyToManyField(null=True, to='research.Metric'),
        ),
    ]
